---
name: Tests

on: push

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, zip
          coverage: none
      - name: Install PHP dependencies
        run: composer update --no-interaction
      - name: Run tests
        run: composer single